### ISSUE TITLE
error makemigrations to 1.0.0 from 0.6.1.

### ISSUE THREAD

**Issue by dictoss** [dictoss/active-task-summary#43]
error makemigrations to 1.0.0 from 0.6.1.

see command log.

$ python manage.py makemigrations ats
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/makemigrations.py", line 96, in handle
    loader = MigrationLoader(None, ignore_no_migrations=True)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 204, in build_graph
    self.load_disk()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 115, in load_disk
    migration_module = import_module("%s.%s" % (module_name, migration_name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/norimitu/repo/github_dictoss/active-task-summary/ats/migrations/0001_initial.py", line 5, in <module>
    import ats.bigint_patch
ImportError: No module named bigint_patch

**Comment by dictoss** [comment]
This bug cause remove ats/bigint_patch.py file.
In 0001_initial.py, generated to "import bigint_patch" line and included model class in bigint_patch.py.

This is the migrate bug.

I will fix it.
